name: package-deploy

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches: 
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup .NET Core @ Latest
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/<organization>/index.json
        dotnet-version: 6.0.x
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Check out Code 
      uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build solution and generate NuGet package
      run: |  
        cd <project>
        dotnet pack --configuration release -o:package /p:PackageVersion=${{ steps.gitversion.outputs.AssemblySemVer }}
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./<project>/out/*.nupkg --skip-duplicate --no-symbols true